### ISSUE TITLE
Proxy doesn't start in Plesk

### ISSUE THREAD

**Issue by jordiweblidera** [ZitRos/save-analytics-from-content-blockers#4] opened 2019-09-05 10:17 UTC
Hello,

I'm trying to configure the proxy in Plesk according to this guide: https://docs.plesk.com/en-US/onyx/customer-guide/nodejs-support.76652/, but it tells me that there is no app.js file. Here I tried to put it pointing to src/api.js, but it doesn't work.

If I'm going to execute script and run "start", I get the following error:

```
> google-tag-manager-proxy@1.0.0 start /var/www/vhosts/domain.com/gtm.domain.com
> node -r esm src/api.js

npm WARN lifecycle The node binary used for scripts is /usr/bin/node but npm is using /opt/plesk/node/8/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
/var/www/vhosts/domain.com/gtm.domain.com/src/api.js:18
export async function init () {

SyntaxError: Unexpected token function
    at Object.Module._extensions..js (module.js:586:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-tag-manager-proxy@1.0.0 start: `node -r esm src/api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-tag-manager-proxy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [/var/www/vhosts/domain.com/.npm/_logs/2019-09-05T10_03_59_393Z-debug.log]
```

I attach the generated log: [2019-09-05T10_03_59_393Z-debug.log](https://github.com/ZitRos/save-analytics-from-content-blockers/files/3578683/2019-09-05T10_03_59_393Z-debug.log)

Regards,
Jordi

**Comment by ZitRos** [comment] 2019-09-05 12:38
Hi @jordiweblidera!

Thanks for your question.

As far as I can see from logs,

> verbose node v8.16.0

Try to upgrade to the latest NodeJS (v10+) first and see if it solves your issue.

Thanks!

**Comment by jordiweblidera** [comment] 2019-09-06 07:55
Hi @ZitRos,

----------

With 10.16.0:

```
> google-tag-manager-proxy@1.0.0 start /var/www/vhosts/domain.com/gtm.domain.com
> node -r esm src/api.js

npm WARN lifecycle The node binary used for scripts is /usr/bin/node but npm is using /opt/plesk/node/10/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
/var/www/vhosts/domain.com/gtm.domain.com/src/api.js:18
export async function init () {

SyntaxError: Unexpected token function
    at Object.Module._extensions..js (module.js:586:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-tag-manager-proxy@1.0.0 start: `node -r esm src/api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-tag-manager-proxy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/vhosts/domain.com/.npm/_logs/2019-09-06T07_47_18_285Z-debug.log
```

[2019-09-06T07_47_18_285Z-debug.log](https://github.com/ZitRos/save-analytics-from-content-blockers/files/3582835/2019-09-06T07_47_18_285Z-debug.log)

----------

With 12.4.0:

```
> google-tag-manager-proxy@1.0.0 start /var/www/vhosts/domain.com/gtm.domain.com
> node -r esm src/api.js

npm WARN lifecycle The node binary used for scripts is /usr/bin/node but npm is using /opt/plesk/node/12/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
/var/www/vhosts/domain.com/gtm.domain.com/src/api.js:18
export async function init () {

SyntaxError: Unexpected token function
    at Object.Module._extensions..js (module.js:586:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-tag-manager-proxy@1.0.0 start: `node -r esm src/api.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-tag-manager-proxy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/vhosts/domain.com/.npm/_logs/2019-09-06T07_50_20_192Z-debug.log
```

[2019-09-06T07_50_20_192Z-debug.log](https://github.com/ZitRos/save-analytics-from-content-blockers/files/3582836/2019-09-06T07_50_20_192Z-debug.log)

----------

Regards,
Jordi

**Comment by ZitRos** [comment] 2019-09-06 08:22
Can you provide any credentials/demo to test it within Plesk? Because it runs perfectly without Plesk. Seems like `esm` is not properly loaded there (it does not understand `export async function` syntax). Try also playing with [esm options](https://www.npmjs.com/package/esm#options) or try another way of [enabling it](https://www.npmjs.com/package/esm#getting-started).

**Comment by jordiweblidera** [comment] 2019-10-17 11:27
Hi @ZitRos, excuse me. I forgot to answer you. Tomorrow I'll give you the plesk data and we'll try to solve it.

**Comment by ZitRos** [comment] 2019-10-21 15:13
@jordiweblidera, any updates? :) If the issue is not actual anymore than just close it. Thanks!

**Comment by ZitRos** [comment] 2020-02-11 21:30
Closed due to inactivity.

**Closed** 2020-02-11 21:30 UTC
